### ISSUE TITLE
All drivers, command prompt blocked

### ISSUE THREAD

**Issue by hariom5463** [surajfale/passthrough-minifilter-driver#1]
After deploying the driver, once usb is blocked, I am not able to access my computer Drivers, cmd.exe, etc.

**Comment by surajfale** [comment]
Ohh man. It was working for me.  I tested it on Windows 7 and XP.  Right now i dont have enough bandwidth to look into issue. 
Also I would like to mention, code is  just for reference do not use directly. As I have built this 2-3 years back.

**Comment by surajfale** [comment]
Ohh man. It was working for me.  I tested it on Windows 7 and XP. Try it on VM instead of host OS. 
 Right now i dont have enough bandwidth to look into issue. 
Also I would like to mention, code is  just for reference do not use directly. As I have built this 2-3 years back. 
But feel free to resolve the issue and let me know about it.

**Comment by hariom5463** [comment]
I tried in VM only over XP. I will try to resolve it.

**Comment by surajfale** [comment]
Please and then let me know
- What was the issue
- What did you do to resolve it.
